RentCar/Models/Entities/Address.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Models.Entities
{
    public class Address : BaseEntity
    {
        public string Country { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Mail { get; set; }
    }
}

RentCar/Models/Entities/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Models.Entities
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

RentCar/Models/Entities/Logo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Models.Entities
{
    public class Logo : BaseEntity
    {
        public string Image { get; set; }
    }
}

RentCar/Models/Entities/PartnerInfoCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Models.Entities
{
    public class PartnerInfoCard : BaseEntity
    {
        public string Image { get; set; }
        public string BrandName { get; set; }
        public string Description { get; set; }
    }
}

RentCar/Models/Entities/Slider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Models.Entities
{
    public class Slider : BaseEntity
    {
        public string Image { get; set; }
    }
}

RentCar/Models/ErrorViewModel.cs
using System;

namespace RentCar.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RentCar/Models/ViewModels/ContactIndexViewModel.cs
using RentCar.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Models.ViewModels
{
    public class ContactIndexViewModel
    {
        public Address Address { get; set; }
    }
}

RentCar/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentCar.DAL;
using RentCar.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext _dbContext;

        public ContactController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            return View(new ContactIndexViewModel { 
                Address = await _dbContext.Addresses.FirstOrDefaultAsync()
            });;
        }
    }
}

RentCar/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Controllers
{
    public class HomeController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

RentCar/Controllers/PartnerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentCar.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.Controllers
{
    public class PartnerController : Controller
    {
        private readonly AppDbContext _dbContext;

        public PartnerController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _dbContext.PartnerInfoCards.ToListAsync());
        }
    }
}

RentCar/ViewComponents/CarouselViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RentCar.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.ViewComponents
{
    public class CarouselViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public CarouselViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            return View(_dbContext.Sliders.ToList());
        }
    }
}

RentCar/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RentCar.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentCar.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public HeaderViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IViewComponentResult Invoke()
        {
            return View(_dbContext.Logos.FirstOrDefault());
        }
    }
}

RentCar/Views/Contact/Index.cshtml
@model ContactIndexViewModel
@{
    ViewData["Title"] = "Index";
}


<!--==================== FORM START ====================-->
<div class="form__container">

    <form class="contact-form">
        <div class="form-header">
            <h1>Bizimlə Əlaqə</h1>
        </div>
        <ul class="form-ul">
            <li>
                <label class="form-lbl" for="name"><span>Ad <span class="required-star">*</span></span></label>
                <input class="form-inp" type="text" id="name" name="user_name">
            </li>
            <li>
                <label class="form-lbl" for="surname"><span>Soyad <span class="required-star">*</span></span></label>
                <input class="form-inp" type="text" id="surname" name="user_surname">
            </li>
            <li>
                <label class="form-lbl" for="mail"><span>Email <span class="required-star">*</span></span></label>
                <input class="form-inp" type="email" id="mail" name="user_email">
            </li>
            <li>
                <label class="form-lbl" for="phone"><span>Telefon <span class="required-star">*</span></span></label>
                <input class="form-inp" type="tel" id="phone" name="user_phone">
            </li>
            <li>
                <label class="form-lbl" for="msg"><span>Mesaj</span></label>
                <textarea class="form-textarea" rows="4" cols="50"></textarea>
            </li>
            <li>
                <input id="form-submit-btn" type="submit" value="Göndər">
            </li>
        </ul>
    </form>

</div>
<!--==================== FORM END ====================-->


<!--==================== MAP ADDRESS START ====================-->
<div class="address__container">

    <div class="item">
        <div class="address">
            <h1>@Model.Address.City/@Model.Address.Country</h1>
            <p>@Model.Address.Location</p>
            <p>Tel: @Model.Address.PhoneNumber / @Model.Address.MobileNumber</p>
            <a href="https://www.instagram.com/vasifcoder/">@Model.Address.Mail</a>
        </div>
    </div>


    <div class="item">
        <div class="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3039.4286744962415!2d49.85175681535471!3d40.3771908793697!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40307d079efb5163%3A0xc20aa51a5f0b5e01!2sCode%20Academy!5e0!3m2!1sen!2s!4v1647447611196!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </div>

</div>
<!--==================== MAP ADDRESS END ====================-->

RentCar/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<!--==================== CARD START ====================-->
<section>
    <div class="box-container">
        <div class="box">
            <div class="image">
                <img src="~/image/cars/black-lamborgini.jpg" alt="">
            </div>
            <div class="info">
                <h4>Lamborghini</h4>
                <h5>Gallardo</h5>
                <mark>Bakı/Nərimanov</mark>
                <p>Avtomobil yaxsi veziyyetdedir. Hec bir problemi yoxdur.</p>
                <span>₼40.00 günlük <s>$50.00</s></span>
                <div class="stars">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star unchecked"></span>
                </div>
            </div>
            <div class="btn">
                <a href="">Detallı</a>
            </div>
        </div>

        <div class="box">
            <div class="image">
                <img src="~/image/cars/white-toyota.jpg" alt="">
            </div>
            <div class="info">
                <h4>Toyota</h4>
                <h5>Camry</h5>
                <mark>Gəncə/Kəpəz</mark>
                <p>Sureti sevenler ucun</p>
                <span>₼20.00 günlük <s>$30.00</s></span>
                <div class="stars">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </div>
            </div>
            <div class="btn">
                <a href="">Detallı</a>
            </div>
        </div>

        <div class="box">
            <div class="image">
                <img src="~/image/cars/bmw-grn.jpg" alt="">
            </div>
            <div class="info">
                <h4>BMW</h4>
                <h5>Mondeo</h5>
                <mark>Bakı/Nəsimi</mark>
                <p>Avtomobil saz veziyyetdedir</p>
                <span>₼35.00 günlük <s>$40.00</s></span>
                <div class="stars">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </div>
            </div>
            <div class="btn">
                <a href="">Detallı</a>
            </div>
        </div>

        <div class="box">
            <div class="image">
                <img src="~/image/cars/mercedes-black-2022.jpg" alt="">
            </div>
            <div class="info">
                <h4>Mercedes</h4>
                <h5>CR-V</h5>
                <mark>Lənkəran/Liman</mark>
                <p>Avtomobil saz veziyyetdedir</p>
                <span>₼20.00 günlük <s>$30.00</s></span>
                <div class="stars">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </div>
            </div>
            <div class="btn">
                <a href="">Detallı</a>
            </div>
        </div>

        <div class="box">
            <div class="image">
                <img src="~/image/cars/audi-ylw.jpg" alt="">
            </div>
            <div class="info">
                <h4>Audi</h4>
                <h5>RS7</h5>
                <mark>Bakı/28 May</mark>
                <p>Avtomobil saz veziyyetdedir</p>
                <span>₼45.00 günlük <s>$55.00</s></span>
                <div class="stars">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </div>
            </div>
            <div class="btn">
                <a href="">Detallı</a>
            </div>
        </div>

        <div class="box">
            <div class="image">
                <img src="~/image/cars/porsche-cayenne.jpg" alt="">
            </div>
            <div class="info">
                <h4>Porsche</h4>
                <h5>Cayenne</h5>
                <mark>Bakı/Səbail</mark>
                <p>Avtomobil saz veziyyetdedir</p>
                <span>₼45.00 günlük <s>$55.00</s></span>
                <div class="stars">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star unchecked"></span>
                    <span class="fa fa-star unchecked"></span>
                </div>
            </div>
            <div class="btn">
                <a href="">Detallı</a>
            </div>
        </div>

    </div>

</section>
<!--==================== CARD END ====================-->


<!--==================== LOADMORE BUTTON START ====================-->
<div class="loadmore__btn">
    <button>Daha Çox</button>
</div>
<!--==================== LOADMORE BUTTON END ====================-->


<!--==================== VIDEO SECTION START ====================-->
<div class="video__section">
    <div class="ads-video">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/33crJ6BiJ20" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
</div>
<!--==================== VIDEO SECTION END ====================-->

RentCar/Views/Partner/Index.cshtml
@model List<PartnerInfoCard>
@{
    ViewData["Title"] = "Index";
}

<!--==================== PARTNERS START ====================-->
<div class="partners-brand-body">

    <div class="partners_brand_container">

        @foreach (var infocard in Model)
        {
            <div class="container fade-in">
                <img src="~/image/@infocard.Image" alt="@infocard.BrandName" class="image">
                <div class="brand-detail">
                    <div class="text">
                        <p><b>@infocard.BrandName</b></p>
                        @Html.Raw(infocard.Description)
                    </div>
                </div>
                <div class="brand-info">
                    <p>@infocard.BrandName</p>
                </div>
            </div>
        }

    </div>
</div>
<!--==================== PARTNERS END ====================-->

RentCar/Views/Shared/Components/Carousel/Default.cshtml
 @model List<Slider>
    
<!--==================== CAROUSEL START ====================-->
<div class="carousel">
    <Section class="img__slider">

        <div class="slider__container">

            @foreach (var slider in Model)
            {
                <div class="slide">
                    <img src="~/image/@slider.Image">
                </div>
            }



        </div>
    </Section>
</div>
<!--==================== CAROUSEL END ====================-->

RentCar/Views/Shared/Components/Header/Default.cshtml
@model Logo

<!--==================== HEADER START ====================-->
<header class="header">
    <div class="navbar__container">
        <nav>
            <div class="logo">
                <img src="~/image/@Model.Image" alt="Logo Image">
            </div>
            <div class="hamburger">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
            <ul class="nav__links">
                <li><a asp-action="Index" asp-controller="Home">Ana səhifə</a></li>
                <li><a href="">Haqqımızda</a></li>
                <li><a asp-action="Index" asp-controller="Partner">Tərəfdaşlarımız</a></li>
                <li><a href="#">Xidmətlər</a></li>
                <li><a asp-action="Index" asp-controller="Contact">Əlaqə</a></li>

                <!--=== darkmode ===-->
                <input type="checkbox" class="checkbox" id="checkbox">
                <label for="checkbox" class="label">
                    <i class="fas fa-moon"></i>
                    <i class="fas fa-sun"></i>
                    <div class="ball"></div>
                </label>
                <!--=== end ===-->

                <li><a class="login__button" href="login.html">Giriş</a></li>
            </ul>
        </nav>
    </div>
</header>
<!--==================== HEADER END ====================-->

RentCar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="az">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== BOOTSTRAP ===============-->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script> -->
    <!--=============== FONT AWESOME ===============-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />

    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/header.css">
    <link rel="stylesheet" href="~/css/carousel.css">
    <link rel="stylesheet" href="~/css/card.css">
    <link rel="stylesheet" href="~/css/darkmode.css">
    <link rel="stylesheet" href="~/css/footer.css">
    <link rel="stylesheet" href="~/css/detail.css">
    <link rel="stylesheet" href="~/css/accordion.css">
    <link rel="stylesheet" href="~/css/loadmore.css">
    <link rel="stylesheet" href="~/css/contact.css">
    <link rel="stylesheet" href="~/css/map.css">
    <link rel="stylesheet" href="~/css/modal.css">
    <link rel="stylesheet" href="~/css/payment.css">
    <link rel="stylesheet" href="~/css/videosection.css">
    <link rel="stylesheet" href="~/css/partners.css">


    <!--=============== ICON ===============-->
    <link rel="shortcut icon" href="~/image/icons/red-car-icon-removebg-preview.png" type="image">
    <title>vsf car rental agency</title>
</head>
<body>

    <div class="wrapper">

        @await Component.InvokeAsync("Header")

        @await Component.InvokeAsync("Carousel")
               
        <!--==================== ACCORDION START ====================-->
        <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-item-header" onmousedown="bleep.play()">
                    <h1>
                        Axtarış et
                    </h1>
                </div>
                <div class="accordion-item-body">
                    <div class="accordion-item-body-content">
                        <form method="post" action="">

                            <!-- select -->
                            <div class="search__select">
                                <select class="select__brand">
                                    <option value="0">Marka seç:</option>
                                    <option value="1">Audi</option>
                                    <option value="2">BMW</option>
                                    <option value="3">Citroen</option>
                                    <option value="4">Ford</option>
                                    <option value="5">Honda</option>
                                    <option value="6">Jaguar</option>
                                    <option value="7">Land Rover</option>
                                    <option value="8">Mercedes</option>
                                    <option value="9">Mini</option>
                                    <option value="10">Nissan</option>
                                    <option value="11">Toyota</option>
                                    <option value="12">Volvo</option>
                                </select>

                                <select class="select__model">
                                    <option value="0">Model seç:</option>
                                    <option value="1">Audi</option>
                                    <option value="2">BMW</option>
                                    <option value="3">Citroen</option>
                                    <option value="4">Ford</option>
                                    <option value="5">Honda</option>
                                    <option value="6">Jaguar</option>
                                    <option value="7">Land Rover</option>
                                    <option value="8">Mercedes</option>
                                    <option value="9">Mini</option>
                                    <option value="10">Nissan</option>
                                    <option value="11">Toyota</option>
                                    <option value="12">Volvo</option>
                                </select>

                                <select class="select__city">
                                    <option value="0">Şəhər seç:</option>
                                    <option value="1">Bakı</option>
                                    <option value="2">Şuşa</option>
                                    <option value="3">Gəncə</option>
                                    <option value="4">Sumqayıt</option>
                                    <option value="5">Lənkəran</option>
                                    <option value="6">Naxçıvan</option>
                                    <option value="7">Balakən</option>
                                    <option value="8">Quba</option>
                                </select>

                                <!-- start date -->
                                <label for="start">Başlanğıc:</label>

                                <input type="date" id="start" name="trip-start">

                                <!-- end date -->
                                <label for="end">Son:</label>

                                <input type="date" id="end" name="trip-start">

                                <!-- price input -->
                                <label for="minPrice">Min:</label>
                                <input type="number" id="minPrice" name="minPrice" min="0">
                                <span>₼</span><br> <br> <br>

                                <label for="maxPrice">Maks:</label>
                                <input type="number" id="maxPrice" name="maxPrice" min="10">
                                <span>₼</span>

                            </div>


                            <!-- submit button -->
                            <div class="submit">
                                <button class="btn" type="submit" value="Submit">Axtar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--==================== ACCORDION END ====================-->

        @RenderBody()

        <!--==================== FOOTER START ====================-->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer__col">
                        <h4>Şirkət</h4>
                        <ul>
                            <li>
                                <a href="#">Haqqımızda</a>
                            </li>
                            <li>
                                <a href="#">Xidmətlərimiz</a>
                            </li>
                            <li>
                                <a href="#">Gizlilik Siyasəti</a>
                            </li>
                            <li>
                                <a href="#">Tərəfdaşlıq Proqramı</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer__col">
                        <h4>Kömək</h4>
                        <ul>
                            <li>
                                <a href="#">Sual-Cavab</a>
                            </li>
                            <li>
                                <a href="#">Daşınma</a>
                            </li>
                            <li>
                                <a href="#">Kompensasiya</a>
                            </li>
                            <li>
                                <a href="#">Sifariş Statusu</a>
                            </li>
                            <li>
                                <a href="payment.html">Ödəniş Növləri</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer__col">
                        <h4>Onlayn Kirayə</h4>
                        <ul>
                            <li>
                                <a href="#">Avtomobil</a>
                            </li>
                            <li>
                                <a href="#">Saat</a>
                            </li>
                            <li>
                                <a href="#">Ev</a>
                            </li>
                            <li>
                                <a href="#">Paltar</a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer__col">
                        <h4>Bizi İzləyin</h4>
                        <div class="social-links">
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a href="https://www.youtube.com/channel/UCPEmMq_L2w9aLN97Vvy_V0Q/videos">
                                <i class="fab fa-youtube"></i>
                            </a>
                            <a href="https://www.instagram.com/vasifcoder/">
                                <i class="fab fa-instagram"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-linkedin-in"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="copyright">
                <p>&copy; Vasif Hüseynov 2022</p>
            </div>
        </footer>
        <!--==================== FOOTER END ====================-->


    </div>

    <!--=============== JAVASCRIPT ===============-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/detail.js"></script>
    <script src="~/js/main.js"></script>

</body>
</html>